from datetime import date
from pathlib import Path
import shutil
import textwrap

import fitz
import yaml


ROOT = Path(__file__).resolve().parent
INPUT = ROOT / "Input"
PDF_PATH = INPUT / "sample_version.pdf"
BACKUP_PATH = INPUT / "sample_version.original.pdf"
SOFTWARE_PATH = INPUT / "software.yml"


VERSION_DATA = {
    "SQL Server 2019": ("15.0.4385.2 / CU32", "Older deployed"),
    "MS Exchange Server 2019": ("15.2.1748.10 / CU15", "Older deployed"),
    "libCurl": ("8.12.1", "Older deployed"),
    "OpenSSL": ("4.0.0", "Latest"),
    "HCL Domino": ("14.5.0", "Latest"),
    "HCL Notes": ("14.5.0", "Latest"),
    "OutLook 2019": ("16.0.10417.20032", "Older deployed"),
    "ElasticSearch": ("9.0.0", "Latest"),
    "edge": ("118.0.2088.76", "Older deployed"),
    "Altova XMLSpy Pro": ("2024r2", "Older deployed"),
    "7-Zip": ("26.00", "Latest"),
    "Acrobat Reader DC": ("25.001.20672", "Latest"),
    "FileZilla": ("3.70.0", "Latest"),
    "FreeMind/Freeplane": ("Freeplane 1.11.14", "Older deployed"),
    "GIMP": ("3.0.4", "Latest"),
    "Inkscape": ("1.4.2", "Latest"),
    "Thingamahoochie WinMerge": ("2.16.48", "Latest"),
    "VLC Media Player": ("3.0.23", "Latest"),
    "WinDirStat": ("2.2.2", "Latest"),
    "XMLPad": ("3.0.4", "Older deployed"),
    "TechSmith Snagit": ("2026.0.0", "Latest"),
    "Adobe Premiere Pro": ("26.0.0", "Latest"),
    "Adobe InDesign": ("21.2.0", "Latest"),
    "Adobe Dreamweaver": ("21.5", "Latest"),
    "Adobe After Effects CC": ("26.0.0", "Latest"),
    "Adobe Illustrator CC": ("30.3.0", "Latest"),
    "Adobe Photoshop CC": ("27.3.0", "Latest"),
    "Adobe XD": ("57.1.12", "Latest"),
    "Adobe Acrobat Professional": ("25.001.20672", "Latest"),
    "Adobe Digital Editions": ("4.5.12", "Older deployed"),
    "Corel Draw Graphics Suite": ("2024 v25.2", "Older deployed"),
    "Corel Draw Technical Suite": ("2024 v25.2", "Older deployed"),
    "Corel Paint Shop Pro": ("2023 25.2.0.58", "Older deployed"),
    "Mindjet MindManager": ("23.1.240", "Older deployed"),
    "Mindjet MindManager Reader": ("22.0.334", "Older deployed"),
    "Kofax PowerPDF Advanced": ("5.1", "Older deployed"),
    "PC Backup(AUD Backup)": ("8.2.1", "Older deployed"),
    "PDF24 Creator": ("11.26.1", "Latest"),
    "Davinci Resolve": ("20.0", "Latest"),
    "Apache Log4j": ("2.25.0", "Latest"),
    "Spring Framework": ("7.0.0", "Latest"),
    "Apache Struts": ("7.0.3", "Latest"),
    "Citrix ADC": ("13.1 build 55.34", "Older deployed"),
    "Microsoft Exchange Server": ("2019 CU15 / 15.2.1748.10", "Older deployed"),
}


def draw_wrapped(page, text, x, y, width, *, font_size=9, color=(0, 0, 0), fontname="helv", line_gap=2):
    max_chars = max(12, int(width / (font_size * 0.46)))
    lines = []
    for paragraph in str(text).splitlines() or [""]:
        lines.extend(textwrap.wrap(paragraph, width=max_chars) or [""])
    for line in lines:
        page.insert_text((x, y), line, fontsize=font_size, fontname=fontname, color=color)
        y += font_size + line_gap
    return y


def new_page(doc):
    page = doc.new_page(width=595, height=842)
    page.draw_rect(fitz.Rect(36, 36, 559, 806), color=(0.82, 0.82, 0.82), width=0.7)
    return page


def render():
    with SOFTWARE_PATH.open("r", encoding="utf-8") as f:
        software = yaml.safe_load(f)

    if PDF_PATH.exists() and not BACKUP_PATH.exists():
        shutil.copy2(PDF_PATH, BACKUP_PATH)

    doc = fitz.open()
    page = new_page(doc)
    y = 58

    page.insert_text((54, y), "System Software and Component Versions Report", fontsize=18, fontname="helv", color=(0.05, 0.09, 0.16))
    y += 26
    page.insert_text((54, y), f"Date: {date.today().isoformat()}", fontsize=10, fontname="helv", color=(0.22, 0.22, 0.22))
    y += 15
    page.insert_text((54, y), "Generated By: Automated System", fontsize=10, fontname="helv", color=(0.22, 0.22, 0.22))
    y += 24
    y = draw_wrapped(
        page,
        "This document lists current and deployed software versions. Items marked Latest are kept at the current target version; items marked Older deployed intentionally remain on older firmware/version levels for compatibility or staged upgrade planning.",
        54,
        y,
        485,
        font_size=9.5,
        color=(0.12, 0.12, 0.12),
    )
    y += 14

    headers = [("Category", 54, 78), ("Software", 136, 190), ("Version / Firmware", 332, 118), ("Status", 462, 76)]

    def table_header(page, y):
        page.draw_rect(fitz.Rect(48, y - 12, 547, y + 8), color=(0.1, 0.18, 0.28), fill=(0.1, 0.18, 0.28))
        for label, x, _ in headers:
            page.insert_text((x, y + 2), label, fontsize=8.8, fontname="helv", color=(1, 1, 1))
        return y + 25

    y = table_header(page, y)
    row_num = 0

    for category, items in software.items():
        for name in items:
            if y > 780:
                page = new_page(doc)
                y = 64
                y = table_header(page, y)
                row_num = 0

            version, status = VERSION_DATA.get(name, ("To be confirmed", "Review"))
            row_top = y - 13
            row_bottom = y + 9
            fill = (0.97, 0.98, 0.99) if row_num % 2 == 0 else (1, 1, 1)
            page.draw_rect(fitz.Rect(48, row_top, 547, row_bottom), color=(0.9, 0.9, 0.9), fill=fill, width=0.3)
            page.insert_text((54, y), category, fontsize=8, fontname="helv", color=(0.18, 0.18, 0.18))
            page.insert_text((136, y), name, fontsize=8, fontname="helv", color=(0.04, 0.04, 0.04))
            page.insert_text((332, y), version, fontsize=8, fontname="helv", color=(0.04, 0.04, 0.04))
            status_color = (0, 0.42, 0.2) if status == "Latest" else (0.56, 0.32, 0.02)
            page.insert_text((462, y), status, fontsize=8, fontname="helv", color=status_color)
            y += 22
            row_num += 1

    y += 8
    if y > 760:
        page = new_page(doc)
        y = 64
    y = draw_wrapped(
        page,
        "Please refer to this document for installed versions before planning updates. Version values should be validated against the target deployment repository before production rollout.",
        54,
        y,
        485,
        font_size=9,
        color=(0.16, 0.16, 0.16),
    )
    page.insert_text((54, y + 16), "End of Report.", fontsize=9, fontname="helv", color=(0.16, 0.16, 0.16))

    tmp = PDF_PATH.with_suffix(".tmp.pdf")
    doc.save(tmp, deflate=True)
    doc.close()
    tmp.replace(PDF_PATH)


if __name__ == "__main__":
    render()
